
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: "category",
      label: "Home",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "introduction",
        },
      ],
    },
    {
      type: "category",
      label: "Console",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "getting_started",
        },
      ],
    },
    {
      type: "category",
      label: "Bridge",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "bridge",
        },
      ],
    },
    {
      type: "category",
      label: "Interact",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "interact",
        },
      ],
    },
    {
      type: "category",
      label: "Calimero SDK",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "calimero_sdk",
        },
      ],
    },
    {
      type: "category",
      label: "KV Oracles",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "oracles",
        },
      ],
    },
    "faq",
  ],
};

module.exports = sidebars;
