/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Calimero Documentation",
  "tagline": "The only blockchain privacy toolkit you will ever need",
  "url": "https://docs.calimero.network",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "facebook",
  "projectName": "docusaurus",
  "plugins": [
    [
      "/Users/chefsale/workspace/docs/node_modules/@docusaurus/plugin-client-redirects/lib/index.js",
      {
        "redirects": []
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/chefsale/workspace/docs/sidebars.js",
          "routeBasePath": "/",
          "editUrl": "https://github.com/calimero-is-near/docs/edit/master"
        },
        "theme": {
          "customCss": "/Users/chefsale/workspace/docs/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "navbar": {
      "logo": {
        "alt": "Calimero Logo",
        "src": "img/logo.svg"
      },
      "items": [],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": null,
          "items": []
        }
      ],
      "copyright": "Copyright © 2022 Calimero Limited."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#f8f8f2",
          "backgroundColor": "#272822"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "#f92672",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "color": "rgb(173, 219, 103)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "#8292a2",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "url"
            ],
            "style": {
              "color": "#a6e22e"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "#f8f8f2"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "#ae81ff"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function",
              "class-name"
            ],
            "style": {
              "color": "#e6db74"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#f8f8f2"
            }
          },
          {
            "types": [
              "selector",
              "doctype"
            ],
            "style": {
              "color": "#a6e22e",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "tag",
              "operator",
              "keyword"
            ],
            "style": {
              "color": "#66d9ef"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "#ae81ff"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)",
              "opacity": 0.7
            }
          },
          {
            "types": [
              "tag",
              "property"
            ],
            "style": {
              "color": "#f92672"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#a6e22e !important"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "#8292a2"
            }
          },
          {
            "types": [
              "rule"
            ],
            "style": {
              "color": "#e6db74"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#f8f8f2",
          "backgroundColor": "#272822"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "#f92672",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "color": "rgb(173, 219, 103)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "#8292a2",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "url"
            ],
            "style": {
              "color": "#a6e22e"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "#f8f8f2"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "#ae81ff"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function",
              "class-name"
            ],
            "style": {
              "color": "#e6db74"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#f8f8f2"
            }
          },
          {
            "types": [
              "selector",
              "doctype"
            ],
            "style": {
              "color": "#a6e22e",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "tag",
              "operator",
              "keyword"
            ],
            "style": {
              "color": "#66d9ef"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "#ae81ff"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)",
              "opacity": 0.7
            }
          },
          {
            "types": [
              "tag",
              "property"
            ],
            "style": {
              "color": "#f92672"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#a6e22e !important"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "#8292a2"
            }
          },
          {
            "types": [
              "rule"
            ],
            "style": {
              "color": "#e6db74"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
